title       = "twitch"
baseURL     = "https://twitch-cli.tamnd.com/"
description = "A command line for twitch."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/twitch-cli"
